import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/ui/CustomCursor/CustomCursor";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased custom-cursor`}>
			<body className="min-h-full flex flex-col">
				<CustomCursor />
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}

/* 
refer my current theme, animations, global.css. complete this selected section. use tailwind not css module for this section. if any images required for this secion, keep it blank. i'll add it later.
*/

/*Page: Aboutus. section: 1. -- full seo friedly content only for "My Expertise". make the contents short, becouse i have lots of other sections and thats make page too long. don't generate sample images. if while generating content, structure the content based on 'what premium animated section look like.' */